col_nuls = {'count_CREDIT_ACTIVE_SK_DATE_DECISION_2',
			'count_CREDIT_ACTIVE_SK_DATE_DECISION_3',
			'count_CREDIT_CURRENCY_SK_DATE_DECISION_chf',
			'count_CREDIT_CURRENCY_SK_DATE_DECISION_eur',
			'count_CREDIT_CURRENCY_SK_DATE_DECISION_usd',
			'max_AMT_REQ_SOURCE_DAY',
			'max_AMT_REQ_SOURCE_WEEK',
			'max_CREDIT_ACTIVE_AMT_CREDIT_MAX_OVERDUE_3',
			'max_CREDIT_CURRENCY_AMT_CREDIT_MAX_OVERDUE_chf',
			'max_CREDIT_CURRENCY_AMT_CREDIT_MAX_OVERDUE_eur',
			'max_CREDIT_CURRENCY_AMT_CREDIT_MAX_OVERDUE_usd',
			'max_CREDIT_TYPE_AMT_CREDIT_MAX_OVERDUE_0',
			'max_CREDIT_TYPE_AMT_CREDIT_MAX_OVERDUE_10',
			'max_CREDIT_TYPE_AMT_CREDIT_MAX_OVERDUE_2',
			'max_CREDIT_TYPE_AMT_CREDIT_MAX_OVERDUE_7',
			'max_CREDIT_TYPE_AMT_CREDIT_MAX_OVERDUE_8',
			'max_CREDIT_TYPE_AMT_CREDIT_MAX_OVERDUE_9',
			'max_CREDIT_TYPE_AMT_CREDIT_MAX_OVERDUE_99',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_0_0',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_0_10',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_0_2',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_0_7',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_0_8',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_0_9',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_1_0',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_1_10',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_1_2',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_1_7',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_1_8',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_1_9',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_2_1',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_2_18',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_2_19',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_2_3',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_2_6',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_2_7',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_2_9',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_2_99',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_3_1',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_3_18',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_3_19',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_3_3',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_3_4',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_3_5',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_0',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_10',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_18',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_2',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_6',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_7',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_8',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_9',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_99',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_1_0',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_1_10',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_1_2',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_1_7',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_1_8',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_1_9',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_1_99',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2_1',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2_18',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2_19',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2_3',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2_4',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2_5',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2_6',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2_7',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2_9',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2_99',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_3_1',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_3_18',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_3_19',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_3_3',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_3_4',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_3_5',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_0_0',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_0_10',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_0_18',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_0_2',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_0_7',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_0_8',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_0_9',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_1_0',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_1_10',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_1_2',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_1_7',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_1_8',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_1_9',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_2_1',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_2_18',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_2_19',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_2_3',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_2_4',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_2_6',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_2_7',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_2_9',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_2_99',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_3_1',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_3_18',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_3_19',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_3_3',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_3_4',
			'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_3_5',
			'mean_CREDIT_ACTIVE_fact_lifetime_3',
			'mean_CREDIT_ACTIVE_plan_lifetime_3',
			'mean_CREDIT_ACTIVE_preschedule_time_3',
			'mean_CREDIT_CURRENCY_fact_lifetime_chf',
			'mean_CREDIT_CURRENCY_fact_lifetime_eur',
			'mean_CREDIT_CURRENCY_fact_lifetime_usd',
			'mean_CREDIT_CURRENCY_plan_lifetime_chf',
			'mean_CREDIT_CURRENCY_plan_lifetime_eur',
			'mean_CREDIT_CURRENCY_plan_lifetime_usd',
			'mean_CREDIT_CURRENCY_preschedule_time_chf',
			'mean_CREDIT_CURRENCY_preschedule_time_eur',
			'mean_CREDIT_TYPE_fact_lifetime_0',
			'mean_CREDIT_TYPE_fact_lifetime_10',
			'mean_CREDIT_TYPE_fact_lifetime_2',
			'mean_CREDIT_TYPE_fact_lifetime_7',
			'mean_CREDIT_TYPE_fact_lifetime_8',
			'mean_CREDIT_TYPE_fact_lifetime_9',
			'mean_CREDIT_TYPE_fact_lifetime_99',
			'mean_CREDIT_TYPE_plan_lifetime_0',
			'mean_CREDIT_TYPE_plan_lifetime_10',
			'mean_CREDIT_TYPE_plan_lifetime_2',
			'mean_CREDIT_TYPE_plan_lifetime_7',
			'mean_CREDIT_TYPE_plan_lifetime_8',
			'mean_CREDIT_TYPE_plan_lifetime_9',
			'mean_CREDIT_TYPE_preschedule_time_0',
			'mean_CREDIT_TYPE_preschedule_time_10',
			'mean_CREDIT_TYPE_preschedule_time_18',
			'mean_CREDIT_TYPE_preschedule_time_2',
			'mean_CREDIT_TYPE_preschedule_time_7',
			'mean_CREDIT_TYPE_preschedule_time_8',
			'mean_CREDIT_TYPE_preschedule_time_9',
			'mean_CREDIT_TYPE_preschedule_time_99',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_0_0',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_0_10',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_0_18',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_0_2',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_0_6',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_0_7',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_0_8',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_0_9',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_0_99',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_1_0',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_1_10',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_1_2',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_1_7',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_1_8',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_1_9',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_2_18',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_2_19',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_2_6',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_2_7',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_2_9',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_2_99',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_3_1',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_3_18',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_3_19',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_3_3',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_3_4',
			'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_3_5',
			'min_CREDIT_ACTIVE_lastcredit_time_3',
			'min_CREDIT_ACTIVE_lastupdate_time_3',
			'min_CREDIT_CURRENCY_lastcredit_time_chf',
			'min_CREDIT_CURRENCY_lastcredit_time_eur',
			'min_CREDIT_CURRENCY_lastcredit_time_usd',
			'min_CREDIT_CURRENCY_lastupdate_time_chf',
			'min_CREDIT_CURRENCY_lastupdate_time_eur',
			'min_CREDIT_CURRENCY_lastupdate_time_usd',
			'min_CREDIT_TYPE_lastcredit_time_0',
			'min_CREDIT_TYPE_lastcredit_time_10',
			'min_CREDIT_TYPE_lastcredit_time_2',
			'min_CREDIT_TYPE_lastcredit_time_7',
			'min_CREDIT_TYPE_lastcredit_time_8',
			'min_CREDIT_TYPE_lastcredit_time_9',
			'min_CREDIT_TYPE_lastupdate_time_0',
			'min_CREDIT_TYPE_lastupdate_time_10',
			'min_CREDIT_TYPE_lastupdate_time_2',
			'min_CREDIT_TYPE_lastupdate_time_7',
			'min_CREDIT_TYPE_lastupdate_time_8',
			'min_CREDIT_TYPE_lastupdate_time_9',
			'sum_CREDIT_ACTIVE_AMT_ANNUITY_3',
			'sum_CREDIT_ACTIVE_AMT_CREDIT_SUM_3',
			'sum_CREDIT_COLLATERAL',
			'sum_CREDIT_CURRENCY_AMT_CREDIT_SUM_DEBT_chf',
			'sum_CREDIT_CURRENCY_AMT_CREDIT_SUM_DEBT_eur',
			'sum_CREDIT_CURRENCY_AMT_CREDIT_SUM_DEBT_usd',
			'sum_CREDIT_CURRENCY_AMT_CREDIT_SUM_chf',
			'sum_CREDIT_CURRENCY_AMT_CREDIT_SUM_eur',
			'sum_CREDIT_CURRENCY_AMT_CREDIT_SUM_usd',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_0',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_10',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_2',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_7',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_8',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_9',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_10',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_2',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_7',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_8',
			'sum_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_9',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_0',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_1',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_10',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_18',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_19',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_2',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_3',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_4',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_5',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_6',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_7',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_8',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_9',
			'sum_CREDIT_TYPE_CREDIT_COLLATERAL_99',
			'sum_fives_0:12',
			'sum_fours_0:12',
			'sum_fours_0:24',
			'sum_fours_0:3',
			'sum_fours_0:36',
			'sum_fours_0:6',
			'sum_threes_0:12',
			'sum_threes_0:24',
			'sum_threes_0:3',
			'sum_threes_0:6'}
col_less_10 = {'max_AMT_REQ_SOURCE_HOUR',
			   'max_CREDIT_ACTIVE_AMT_CREDIT_MAX_OVERDUE_2',
			   'max_CREDIT_TYPE_AMT_CREDIT_MAX_OVERDUE_18',
			   'max_CREDIT_TYPE_AMT_CREDIT_MAX_OVERDUE_3',
			   'max_worst_status_12m',
			   'max_worst_status_24m',
			   'max_worst_status_36m',
			   'max_worst_status_6m',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_0_18',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_0_6',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_0_99',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_1_6',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_1_99',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_2_5',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_1',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_19',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_3',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_0_4',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_1_6',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_0_6',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_0_99',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_1_6',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_1_99',
			   'mean_CREDIT_ACTIVE_CREDIT_TYPE_plan_lifetime_2_5',
			   'mean_CREDIT_ACTIVE_fact_lifetime_1',
			   'mean_CREDIT_ACTIVE_preschedule_time_2',
			   'mean_CREDIT_CURRENCY_preschedule_time_usd',
			   'mean_CREDIT_TYPE_fact_lifetime_18',
			   'mean_CREDIT_TYPE_fact_lifetime_6',
			   'mean_CREDIT_TYPE_plan_lifetime_99',
			   'mean_CREDIT_TYPE_preschedule_time_6',
			   'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_1_6',
			   'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_1_99',
			   'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_2_1',
			   'min_CREDIT_ACTIVE_CREDIT_TYPE_lastcredit_time_2_3',
			   'min_CREDIT_TYPE_lastcredit_time_6',
			   'sum_CREDIT_TYPE_AMT_CREDIT_SUM_18',
			   'sum_CREDIT_TYPE_AMT_CREDIT_SUM_99',
			   'sum_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_6',
			   'sum_CREDIT_TYPE_AMT_CREDIT_SUM_DEBT_99',
			   'sum_fives_0:24',
			   'sum_fives_0:3',
			   'sum_fives_0:36',
			   'sum_fives_0:48',
			   'sum_fives_0:6',
			   'sum_fives_0:60',
			   'sum_fours_0:48',
			   'sum_threes_0:36',
			   'sum_twos_0:12',
			   'sum_twos_0:24'
			   }

RANDOM_STATE = 2017
# params_xgb = {
# 	'max_depth': 6,
# 	'min_child_weight': 6,
# 	'gamma': 0.0,
# 	'colsample_bytree': 0.8,
# 	'subsample': 0.6,
# 	'scale_pos_weight':1,
# 	'objective':'binary:logistic',
# 	'eta': 0.01,
# 	'alpha': 0.4,
# 	'lambda': 1,
# 	'eval_metric':'auc',
# 	#'silent': 1,
# 	'verbose_eval': True,
# 	'seed': RANDOM_STATE
# }

params_xgb = {
	'max_depth': 4,
	'min_child_weight': 6,
	'gamma': 0.05,
	'colsample_bytree': 1,
	'subsample': 0.6,
	'scale_pos_weight':1,
	'objective':'binary:logistic',
	'eta': 0.01,
	'alpha': 0.9,
	'lambda': 0.6,
	'eval_metric':'auc',
	#'silent': 1,
	'verbose_eval': True,
	'seed': RANDOM_STATE
}

params_lgb = {'num_leaves': 61,
			  'lambda_l1': 7.4691454243437e-05,
			  'learning_rate': 0.005,
			  'lambda_l2': 7.230484155948516e-05,
			  'seed': 2017,
			  'min_data_in_leaf': 55,
			  'bagging_fraction': 0.7685951513380386,
			  'min_sum_hessian_in_leaf': 7.323007453873621,
			  'feature_fraction': 0.9728211591620646,
			  'metric' : 'auc'
			  }